#!/usr/bin/env bash
# script that gives you information about the school file
myFile="school"
if [[ -f "$myFile" ]]; then
  echo "school file exists"
  if [[ -s "$myFile" ]]; then
    echo "school file is not empty"
    echo "school is a regular file"
  else
    echo "school file is empty"
  fi
  if [ -f "$myFile" ]; then
        echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
